//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automation.DataTable {
    
    
    [System.SerializableAttribute()]
    public class SkillTableRow : Utility.DataTable.DataTableRow {
        
        public string Type;
        
        public string Name;
        
        public string Description;
        
        public float CoolTime;
        
        public Utility.DataStructure.SerializedDictionary<string, float> SkillDatas;
    }
}
