Dialogue_0006 = CreateDialog(function()

    Talk("A", "…들어왔다.")
    Talk("B", "음… 왜 이렇게 조용하지?")
    Talk("B", "마치 뭔가 나타나기라도 할 듯이…")
    Talk("A", "뭐, 뭐야?")
    Talk("B", "엄청난 땅울림이네!")
    Talk("C", "…식별코드 설정.")
    Talk("C", "완료.")
    Talk("C", "목표물, 폐기물 CODE.")
    Talk("C", "처분을 시작합니다.")
    Talk("B", "우리가 올 줄 알았던 거야.")
    Talk("B", "어쩔 수 없지… 쓰러뜨리자!")

end)